# Generated by Django 4.2.14 on 2024-08-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='photo',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='photo',
            new_name='outfit_image',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='title',
            new_name='outfit_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='description',
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_favorited',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='outfit_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
