# Generated by Django 4.2.14 on 2024-08-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_photo_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='is_kid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
