# Generated by Django 4.2.14 on 2024-08-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_favorite_outfit_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_photo',
            new_name='user_image',
        ),
    ]
