# Generated by Django 4.2.14 on 2024-08-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_outfit_subtitle_outfit_describtion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='describtion',
            new_name='description',
        ),
    ]
