# Generated by Django 4.2.14 on 2024-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_describtion_outfit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='outfit_image',
        ),
        migrations.RemoveField(
            model_name='part',
            name='link',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.RemoveField(
            model_name='part',
            name='outfit',
        ),
        migrations.AddField(
            model_name='part',
            name='outfit_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/outfit_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_images'),
        ),
    ]
