# Generated by Django 4.2.14 on 2024-08-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_outfit_outfit_image_remove_part_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='outfit_image',
        ),
        migrations.AddField(
            model_name='part',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='outfit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_parts', to='accounts.outfit'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OutfitImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit_image', models.ImageField(blank=True, null=True, upload_to='images/outfit_images')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_images', to='accounts.outfit')),
            ],
        ),
    ]
