# Generated by Django 3.2.9 on 2024-07-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='MEMBERS',
        ),
    ]
