# Generated by Django 3.2.9 on 2024-07-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catg_Title', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OUTFIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('Gender', models.CharField(max_length=10)),
                ('Outfit_Photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('User_Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=128)),
                ('Gender', models.CharField(max_length=10)),
                ('Birthday', models.DateField()),
                ('Register_Date', models.DateField(auto_now_add=True)),
                ('Biography', models.TextField(max_length=250)),
                ('Email', models.EmailField(max_length=200)),
                ('User_Photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_Name', models.CharField(max_length=50)),
                ('Link', models.CharField(max_length=250)),
                ('Subtitle', models.TextField(max_length=250)),
                ('Outfit_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.outfit')),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.user'),
        ),
        migrations.CreateModel(
            name='FOLLOWER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Who_Followed_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='model_app.user')),
                ('Who_Follows_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='model_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='FAVORITE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Outfit_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.outfit')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_app.user')),
            ],
        ),
    ]
