# Generated by Django 3.2.9 on 2024-07-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='Who_Followed_Id',
            new_name='Followed_Id',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='Who_Follows_Id',
            new_name='Follows_Id',
        ),
        migrations.AddField(
            model_name='category',
            name='Catg_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='Link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
