# Generated by Django 3.2.9 on 2024-07-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_auto_20240728_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='Subtitle',
            field=models.TextField(),
        ),
    ]
