# Generated by Django 4.2.14 on 2024-08-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0013_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USER',
            new_name='UserModa',
        ),
    ]
