# Generated by Django 4.2.14 on 2024-08-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0014_rename_user_usermoda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModa',
            new_name='User',
        ),
    ]
